# Generated by Django 6.0.2 on 2026-05-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('chairperson', 'Chairperson'), ('vice_chair', 'Vice Chairperson'), ('secretary', 'Secretary'), ('member', 'Member')], default='member', max_length=50)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
