# Generated by Django 6.0.2 on 2026-05-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='committee_avatars/')),
                ('position', models.CharField(choices=[('member', 'Committee Member'), ('head', 'Head Committee'), ('secretary', 'Secretary')], default='member', max_length=20)),
                ('committee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
