# Generated by Django 6.0.2 on 2026-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeprofile',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
