# Generated by Django 6.0.2 on 2026-05-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeprofile',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='committeeprofile',
            name='term_start',
        ),
        migrations.RemoveField(
            model_name='committeeprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='committeeprofile',
            name='position',
            field=models.CharField(choices=[('head', 'Head Committee'), ('member', 'Committee Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='CommitteeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_votes', to='main.loanapplication')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='committee.committeeprofile')),
            ],
            options={
                'unique_together': {('application', 'committee_member')},
            },
        ),
    ]
