# Generated by Django 6.0.2 on 2026-05-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_remove_committeeprofile_term_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='committee_avatars/'),
        ),
        migrations.AddField(
            model_name='committeeprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='committeeprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='committeeprofile',
            name='committee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='committeeprofile',
            name='position',
            field=models.CharField(choices=[('member', 'Committee Member'), ('head', 'Head Committee'), ('secretary', 'Secretary')], default='member', max_length=20),
        ),
        migrations.DeleteModel(
            name='CommitteeVote',
        ),
    ]
