# Generated by Django 6.0.2 on 2026-05-13 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(choices=[('loan_officer', 'Loan Officer'), ('collections_officer', 'Collections Officer'), ('credit_investigator', 'Credit Investigator'), ('branch_manager', 'Branch Manager'), ('supervisor', 'Supervisor'), ('cashier', 'Cashier')], default='loan_officer', max_length=100)),
                ('department', models.CharField(default='Loans', max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_backup_codes', models.JSONField(blank=True, default=list)),
                ('otp_enabled_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_application', 'New Application'), ('committee_decision', 'Committee Decision'), ('manager_decision', 'Manager Decision'), ('payment_received', 'Payment Received'), ('overdue_alert', 'Overdue Alert'), ('restructuring_request', 'Restructuring Request'), ('system_alert', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestructuringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=20, unique=True)),
                ('member_id', models.IntegerField()),
                ('old_loan_id', models.IntegerField()),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('old_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_overdue', models.IntegerField(default=0)),
                ('new_charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_term_months', models.IntegerField(default=12)),
                ('new_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('supporting_documents', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending_staff', 'Pending Staff Review'), ('with_committee', 'With Committee'), ('committee_approved', 'Committee Approved'), ('committee_rejected', 'Committee Rejected'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_staff', max_length=20)),
                ('staff_approved', models.BooleanField(default=False)),
                ('committee_approved', models.BooleanField(default=False)),
                ('committee_approved_by_id', models.IntegerField(null=True)),
                ('committee_approved_date', models.DateField(null=True)),
                ('manager_approved', models.BooleanField(default=False)),
                ('manager_approved_by_id', models.IntegerField(null=True)),
                ('manager_approved_date', models.DateField(null=True)),
                ('new_loan_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('staff_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructuring_staff', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_number', models.CharField(max_length=20, unique=True)),
                ('member_id', models.IntegerField()),
                ('loan_id', models.IntegerField()),
                ('amount_to_collect', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('next_due_date', models.DateField()),
                ('is_printed', models.BooleanField(default=False)),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_by_payment_id', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_instructions', to='staff.staffprofile')),
            ],
        ),
    ]
