# Generated by Django 6.0.2 on 2026-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('loan_officer', 'Loan Officer'), ('collections_officer', 'Collections Officer'), ('credit_investigator', 'Credit Investigator'), ('branch_manager', 'Branch Manager'), ('supervisor', 'Supervisor'), ('cashier', 'Cashier')], default='loan_officer', max_length=100),
        ),
    ]
