# Generated by Django 6.0.2 on 2026-05-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='account_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='civil_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employment_status',
            field=models.CharField(default='member', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='max_active_loans',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='max_regular_loan',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=15),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='max_salary_loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='member_tier',
            field=models.CharField(default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='salary_loan_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='verification_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
