# Generated by Django 6.0.2 on 2026-06-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='civil_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='date_hired',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='max_active_loans',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='max_regular_loan',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='max_salary_loan',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='member_tier',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='position',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='salary_loan_eligible',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='loan',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Notes from staff/manager about what needs revision', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Notes from staff/manager about what needs revision', null=True),
        ),
    ]
