# Generated by Django 6.0.2 on 2026-05-12 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_otp_backup_codes_member_otp_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('request_revision', 'Request Revision')], max_length=20)),
                ('approved_line', models.DecimalField(blank=True, decimal_places=2, help_text='Approved loan amount (for approve votes only)', max_digits=12, null=True)),
                ('reduction_reason', models.TextField(blank=True, help_text='Reason if approved amount is less than requested', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection or revision request', null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_votes', to='main.loanapplication')),
                ('committee_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Vote',
                'verbose_name_plural': 'Committee Votes',
                'ordering': ['-voted_at'],
                'unique_together': {('application', 'committee_member')},
            },
        ),
    ]
