# Generated by Django 6.0.2 on 2026-06-23 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_revision_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoMakerConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('confirmation_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_maker_applications', to='main.member')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_maker_confirmations', to='main.loanapplication')),
                ('co_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_maker_confirmations', to='main.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application', 'co_maker')},
            },
        ),
    ]
