# Generated by Django 5.2.13 on 2026-05-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auditlog_account_status_auditlog_civil_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approved_line',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Approved Line Amount'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='committee_approved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Committee Approval Date'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='committee_reduction_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Reduction'),
        ),
    ]
