# Generated by Django 6.0.2 on 2026-05-14
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_loanapplication_approved_line_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (
                        SELECT 1 
                        FROM information_schema.columns 
                        WHERE table_name='main_loanapplication' 
                        AND column_name='approved_line'
                    ) THEN 
                        ALTER TABLE main_loanapplication 
                        ADD COLUMN approved_line decimal(12,2) NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE main_loanapplication DROP COLUMN IF EXISTS approved_line;"
        ),
    ]