# Generated by Django 6.0.2 on 2026-06-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_co_maker_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_offered',
            field=models.TextField(blank=True, help_text='Description of collateral offered', null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_term',
            field=models.IntegerField(default=12, help_text='Loan term in months'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mode_of_payment',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi-annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('committee', 'With Committee'), ('pending_staff_review', 'Pending Staff Review'), ('needs_revision', 'Needs Revision'), ('manager_approved', 'Manager Approved')], default='pending', max_length=30),
        ),
    ]
