# Generated by Django 6.0.2 on 2026-05-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_loanapplication_approved_line_and_more'),
    ]

    operations = [
    ]
