# Generated by Django 6.0.2 on 2026-05-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='manager_profiles/')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('otp_backup_codes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager Profile',
                'verbose_name_plural': 'Manager Profiles',
            },
        ),
    ]
