# Generated by Django 6.0.2 on 2026-05-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerprofile',
            options={},
        ),
    ]
